  - name: Update  apt packages
    ansible.builtin.apt:
      update_cache: yes

  - name: Install nginx
    ansible.builtin.apt:
      name: "{{ item }}"
      state: latest 
    loop: 
      - nginx
      - python
      - awscli
      
  - name: Change Nginx Configuration file   
    ansible.builtin.template:
      src: files/nginx.conf.j2
      dest: {{" nginx_path "}}

  - name: Ensure Python3 pip is installed
    ansible.builtin.apt:
      name: python3-pip
      state: present

  - name: Install botocore and boto3 
    ansible.builtin.pip:
      name: "{{ item }}"
    loop:  
      - botocore
      - boto3   
