name: Upload to S3
on:
    push:
      branches:
        - git-actions
    pull_request:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
    AWS_DEFAULT_REGION: us-east-1

jobs:
    create-resources:
      runs-on: ubuntu-latest
        
      steps:
        - name: Checkout 
          uses: actions/checkout@v3
            
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v1
          
        - name: Terraform init
          run: |
            cd terraform
            terraform init
        
        - name: Terraform plan
          run: |
            cd terraform
            terraform plan -var-file="var.tfvars" 

        - name: Terraform apply 
          run: |
            cd terraform
            terraform apply -var-file="var.tfvars" -auto-approve 
            
    add-to-s3:
      needs: create-resources
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Configure aws credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}  
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }} 
            aws-session-token: ${{ env.AWS_SESSION_TOKEN }}  
            aws-region: ${{ env.AWS_DEFAULT_REGION }}

        - name: Copying files to s3 bucket
          run: aws s3 cp . s3://sujata-pipeline --recursive

    configure-ec2:
      needs: add-to-s3
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v1

        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
            aws-region:  ${{ env.AWS_DEFAULT_REGION }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Ansible Playbook
          run: |
            cd ansible
            ansible-playbook -i aws_ec2.yml playbook.yml
            


        
              

           
