name: Upload to S3
on:
    push:
      
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
    AWS_DEFAULT_REGION: us-east-1

jobs:
    create-resources:
      runs-on: ubuntu-latest
        
      steps:
        - name: Checkout 
          uses: actions/checkout@v1
            
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v1
          
        - name: Terraform init
          run: |
            cd Terraform
            terraform init

        - name: Terraform apply 
          run: |
            cd Terraform
            terraform apply -var-file="var.tfvars" -auto-approve
         

    add-to-s3:
      needs: create-resources
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Configure aws credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  
            aws-region: us-east-1

        - name: Copying files to s3 bucket
          run: aws s3 sync . s3://sujata-pipeline

    configure-ec2:
      needs: add-to-s3
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ env.awsAccessKeyId }}
            aws-secret-access-key: ${{ env.awsSecretAccessKey }}
            aws-session-token: ${{ env.awsSessionToken }}
            aws-region: us-east-1

        - name: Install Ansible
          run: |
            pip install boto3
            pip install ansible  

        - name: Run Ansible Playbook
          run: |
            cd Ansible
            ansible-playbook -i aws_ec2.yml playbook.yml
            


        
              

           